title: Diego Stewart
description: Data Architect • SaaS Builder • Technical Writer
baseurl: ""
url: "https://diego-stewart.github.io"
markdown: kramdown
permalink: /:title/
paginate: 10          # posts per page
paginate_path: "/page/:num/"